"""initial: 12 таблиц по §6 ТЗ

Revision ID: 0001
Revises:
Create Date: 2026-08-23 18:38:33.689072+00:00

Замечания по переносимости (миграция должна работать и на SQLite, и на PostgreSQL):
- `sa.func.now()` рендерится как CURRENT_TIMESTAMP на SQLite и now() на PostgreSQL;
- Enum'ы объявлены с `native_enum=False` -> это VARCHAR + CHECK, поэтому в
  PostgreSQL не создаются отдельные типы и downgrade их не удаляет;
- индексы создаются через `batch_alter_table` (требование SQLite).
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_telegram_id'), ['actor_telegram_id'], unique=False)
        batch_op.create_index('ix_audit_log_entity_entity_id', ['entity', 'entity_id'], unique=False)

    op.create_table('job_locks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_job_locks'))
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('price_stars', sa.Integer(), nullable=False),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name='uq_plans_code')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('percent', 'fixed', 'days', name='promo_type', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes')),
    sa.UniqueConstraint('code', name='uq_promo_codes_code')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('country_flag', sa.String(length=16), nullable=False),
    sa.Column('xui_base_url', sa.String(length=512), nullable=False),
    sa.Column('xui_username', sa.String(length=128), nullable=False),
    sa.Column('xui_password', sa.String(length=512), nullable=False),
    sa.Column('server_host', sa.String(length=255), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=False),
    sa.Column('sub_url', sa.String(length=512), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers')),
    sa.UniqueConstraint('code', name='uq_servers_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('balance_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('trial_used', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_blocked_bot', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_users_referrer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name='uq_users_telegram_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_referrer_id'), ['referrer_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('xui_client_uuid', sa.String(length=64), nullable=False),
    sa.Column('xui_email', sa.String(length=128), nullable=False),
    sa.Column('xui_sub_id', sa.String(length=64), nullable=False),
    sa.Column('xui_inbound_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'disabled', 'deleted', name='subscription_status', native_enum=False, length=32), nullable=False),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('traffic_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reissued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_3d', sa.Boolean(), nullable=False),
    sa.Column('notified_1d', sa.Boolean(), nullable=False),
    sa.Column('notified_3h', sa.Boolean(), nullable=False),
    sa.Column('notified_expired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_subscriptions_server_id_servers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('xui_email', name='uq_subscriptions_xui_email')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_server_id'), ['server_id'], unique=False)
        batch_op.create_index('ix_subscriptions_status_expires_at', ['status', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_subscriptions_user_id_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_xui_client_uuid'), ['xui_client_uuid'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'answered', 'closed', name='ticket_status', native_enum=False, length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('admin_message_id', sa.BigInteger(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('ix_tickets_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Enum('yookassa', 'stars', 'manual', 'balance', name='payment_provider', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', 'canceled', name='payment_status', native_enum=False, length=32), nullable=False),
    sa.Column('amount_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('discount_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('amount_stars', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('local_code', sa.String(length=32), nullable=False),
    sa.Column('confirmation_url', sa.String(length=1024), nullable=True),
    sa.Column('receipt_file_id', sa.String(length=256), nullable=True),
    sa.Column('provision_status', sa.Enum('none', 'pending', 'done', 'failed', name='provision_status', native_enum=False, length=32), nullable=False),
    sa.Column('provision_attempts', sa.Integer(), nullable=False),
    sa.Column('provision_next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provision_error', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_payments_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], name=op.f('fk_payments_promo_id_promo_codes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_payments_server_id_servers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payments_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('external_id', name='uq_payments_external_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_local_code'), ['local_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index('ix_payments_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_payments_user_id_status', ['user_id', 'status'], unique=False)

    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('is_from_admin', sa.Boolean(), nullable=False),
    sa.Column('author_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_messages_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_messages'))
    )
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_messages_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('promo_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_promo_uses_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], name=op.f('fk_promo_uses_promo_id_promo_codes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_promo_uses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_uses'))
    )
    with op.batch_alter_table('promo_uses', schema=None) as batch_op:
        batch_op.create_index('ix_promo_uses_promo_id_user_id', ['promo_id', 'user_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('reward_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_referrals_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], name=op.f('fk_referrals_referee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_referrals_referrer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('payment_id', name='uq_referrals_payment_id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_referee_id'), ['referee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index('ix_referrals_referrer_id_paid', ['referrer_id', 'paid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index('ix_referrals_referrer_id_paid')
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referee_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('promo_uses', schema=None) as batch_op:
        batch_op.drop_index('ix_promo_uses_promo_id_user_id')

    op.drop_table('promo_uses')
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_messages_ticket_id'))

    op.drop_table('ticket_messages')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_user_id_status')
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_subscription_id'))
        batch_op.drop_index('ix_payments_status_created_at')
        batch_op.drop_index(batch_op.f('ix_payments_plan_id'))
        batch_op.drop_index(batch_op.f('ix_payments_local_code'))

    op.drop_table('payments')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_user_id'))
        batch_op.drop_index('ix_tickets_status_created_at')

    op.drop_table('tickets')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_xui_client_uuid'))
        batch_op.drop_index('ix_subscriptions_user_id_status')
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index('ix_subscriptions_status_expires_at')
        batch_op.drop_index(batch_op.f('ix_subscriptions_server_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referrer_id'))

    op.drop_table('users')
    op.drop_table('servers')
    op.drop_table('promo_codes')
    op.drop_table('plans')
    op.drop_table('job_locks')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity_entity_id')
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
